### ISSUE TITLE
PR hygiene

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/parity-processbot#216]
The process bot should ensure some (configurable) PR hygiene:

1. if a PR hasn't seen activity for more than 14days: post a comment to the author, asking them to pick it up again.
2. if a PR hasn't seen activity for another 7 days after that: tag it as `stale`
3. if a PR hasn't seen activity for 14days after it was marked as `stale`: close the PR

Reopening and removing the `on-ice` tag are activities and must be counted in, but if the PR is reopened the clocks starts ticking again. Comments by the process bot are not considered activity.

Best would be to allow a configuration file to describe the specific stages and markers.

**Comment by kianenigma** [comment]
Note: 

at least now that we have recently started with audits, the queue is a bit long and some old PRs could take a while, specially if we keep adding more high priority ones that need to fo before. 

Thus, I think an _approved_ pr awaiting _only_ `needs-audit`, should be exempt or have a longer slack period where it won't be closed.

**Comment by pepyakin** [comment]
Isn't the `on-ice` label supposed to be used under similar but different circumstances? E.g. when the author (or somebody else, actually) wants to indicate that this PR should not be merged because of some blocker. E.g. if the PR in question cannot be merged until some other PR goes through to fix an issue.

If we do need a tag for this situation I'd go with a new tag for that case. Perhaps it could be called "stale"

**Comment by kianenigma** [comment]
Yeah, I think `stale` is correct here not `on-ice`, and I think `on-ice` is also again something foe which there should be an exception :D

**Comment by gilescope** [comment]
Nice spot JP: https://github.com/marketplace/stale looks like it would do the job.

**Comment by gnunicorn** [comment]
> Nice spot JP: https://github.com/marketplace/stale looks like it would do the job.

@kirushik can we enable this bot on the substrate repo? Happy to configure it!

**Comment by kirushik** [comment]
@gnunicorn added (explicitly to the paritytech/substrate for now, please get in touch if there's a need to add it to others).

Per documentation,

> After installing the app, create .github/stale.yml in the default branch to enable it:
> 
```yml
# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
```

Please create that Yaml file with intended values to complete the installation
